from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field
from app.schemas.evidence import EvidenceQualityReport, EvidenceWord


class SourceCitation(BaseModel):
    """
    Provenance source citation linking an answer claim to a document page, OCR confidence,
    and exact bounding box tokens on the physical page.
    """
    page: int = Field(..., ge=1, description="Source page number in document")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Mean OCR confidence of cited evidence")
    flagged: bool = Field(default=False, description="True if cited evidence contains low-confidence OCR text")
    chunk_id: Optional[str] = Field(default=None, description="Internal chunk UUID")
    document_id: Optional[str] = Field(default=None, description="Parent document UUID")
    document_name: Optional[str] = Field(default=None, description="Source document filename")
    evidence_text: Optional[str] = Field(default=None, description="Exact supporting sentence or excerpt")
    risk: Optional[str] = Field(default="LOW", description="Risk level (LOW, MEDIUM, HIGH)")
    tokens: List[EvidenceWord] = Field(
        default_factory=list,
        description="Individual OCR tokens in the supporting evidence with bounding boxes [x0, y0, x1, y1] and confidences"
    )
    page_width: Optional[float] = Field(default=595.0, description="Original page width in PDF/pixel units")
    page_height: Optional[float] = Field(default=842.0, description="Original page height in PDF/pixel units")


class QueryRequest(BaseModel):
    """
    Incoming search / query request from client.
    """
    query: str = Field(..., min_length=2, max_length=1000, description="User question about document(s)")
    document_id: Optional[str] = Field(default=None, description="Optional document ID to scope query")
    use_confidence_reranking: bool = Field(
        default=True,
        description="Whether to use confidence propagation & reranking (Proposed) or standard RAG (Baseline)"
    )


class LLMStructuredOutput(BaseModel):
    """
    Internal structured schema expected from LLM generation.
    """
    answer: str = Field(..., description="Grounded natural language answer with page citations")
    sources: List[SourceCitation] = Field(default_factory=list, description="Citations supporting answer")
    overall_warning: Optional[str] = Field(
        default=None,
        description="Explicit warning if answer relies on uncertain OCR tokens"
    )


class QueryResponse(BaseModel):
    """
    Complete structured response returned by /query endpoint.
    """
    query: str = Field(..., description="Original user query")
    answer: str = Field(..., description="Grounded answer text")
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall answer reliability score (derived from evidence confidence and model certainty)"
    )
    semantic_similarity: Optional[float] = Field(
        default=None,
        description="Semantic relevance match between user query and retrieved document evidence"
    )
    ocr_confidence: Optional[float] = Field(
        default=None,
        description="Mean optical character recognition confidence across supporting evidence"
    )
    risk_level: Literal["LOW_RISK", "MEDIUM_RISK", "HIGH_RISK"] = Field(
        ...,
        description="Risk category for user badging: LOW_RISK (Green), MEDIUM_RISK (Amber), HIGH_RISK (Red)"
    )
    sources: List[SourceCitation] = Field(default_factory=list, description="List of source page citations")
    overall_warning: Optional[str] = Field(
        default=None,
        description="Human-readable warning banner for unverified facts"
    )
    evidence_report: Optional[EvidenceQualityReport] = Field(
        default=None,
        description="Detailed evidence quality metrics with token-level bounding boxes"
    )
    mode: Literal["confidence_aware", "baseline"] = Field(
        default="confidence_aware",
        description="Execution mode: confidence-aware proposed method vs baseline standard RAG"
    )
    execution_time_ms: float = Field(default=0.0, description="Total end-to-end query processing latency in ms")


class BaselineAnswer(BaseModel):
    """
    Representation of answer generated by Baseline Conventional RAG
    (No OCR confidence reranking, no token risk analysis, no uncertainty warnings).
    """
    answer: str = Field(..., description="Answer from Baseline RAG")
    sources: List[int] = Field(default_factory=list, description="List of cited page numbers")
    top_chunk_similarity: float = Field(default=0.0, description="Semantic cosine similarity of top chunk")
    warning: Optional[str] = Field(default=None, description="Always None in baseline RAG")
    latency_ms: float = Field(default=0.0, description="Baseline execution latency in ms")


class ComparisonResponse(BaseModel):
    """
    Side-by-Side Comparison between Baseline Conventional RAG and Proposed Confidence-Aware RAG.
    """
    query: str = Field(..., description="User query evaluated")
    document_id: Optional[str] = Field(default=None, description="Document ID evaluated")
    baseline: BaselineAnswer = Field(..., description="Baseline Conventional RAG result")
    confidence_aware: QueryResponse = Field(..., description="Proposed Confidence-Aware RAG result")
    key_difference: str = Field(
        default="Confidence-Aware RAG identified OCR reliability risks and flagged uncertain tokens, whereas Baseline RAG asserted potentially corrupted text without warning.",
        description="Summary of pipeline decision divergence"
    )
