"""
MongoDB Collection Names & Accessors for Confidence-Aware RAG.
"""

DOCUMENTS_COLLECTION = "documents"
PAGES_COLLECTION = "pages"
OCR_TOKENS_COLLECTION = "ocr_tokens"
CHUNKS_COLLECTION = "chunks"
QUERIES_COLLECTION = "queries"
EVIDENCE_COLLECTION = "evidence"
EVALUATIONS_COLLECTION = "evaluations"

ALL_COLLECTIONS = [
    DOCUMENTS_COLLECTION,
    PAGES_COLLECTION,
    OCR_TOKENS_COLLECTION,
    CHUNKS_COLLECTION,
    QUERIES_COLLECTION,
    EVIDENCE_COLLECTION,
    EVALUATIONS_COLLECTION,
]
